WIP

diff --git a/xnat2fw/syncDicom2FW b/xnat2fw/syncDicom2FW
--- a/xnat2fw/syncDicom2FW
+++ b/xnat2fw/syncDicom2FW
@@ -15,8 +15,6 @@ cmd=$(basename $0)
 
 syntax="$cmd [-D depth][-d dir] [-F]{-g FWGroupID}[-l][-n][-P XNATProject]{-p FlyWheelProject}[-q][-s cessionfile][-t NumberOfTransferThreads][-w NumberOfWorkerThreads][-v] [[XNATSession] ...]"
 
-XNATBaseDir=/data/XNAT/archive
-
 : <<=cut
 =pod
 
@@ -134,12 +132,57 @@ function syncDicom2FW {
 	done
 }
 
+function xnatPrefix {
+    local Group="$1"
+    local Project="$2"
+
+    XNATURL=http://picsl-xnat.uphs.upenn.edu
+    XNATSessionID=$(curl -n -s "$XNATURL/data/JSESSION")
+
+    HTTPCode=$(curl -b "JSESSIONID=$XNATSessionID" -s -o /dev/null -w "%{http_code}" "${XNATURL}/data/projects/${Project}")
+    if [ "$HTTPCode" == 401 ]
+    then
+        echo "$cmd : XNAT authorization failed '$XNATURL'" 1>&2
+        cleanup
+        exit 1
+    fi
+
+    XNATCSVFile=$(sys mktemp /tmp/xnat2fw-XXXXX)
+
+    sys curl -s -b "JSESSIONID=$XNATSessionID" "$XNATURL/data/archive/projects/${Project}/experiments?columns=subject_label,label&format=csv" > $XNATCSVFile
+
+    echo "$XNATCSVFile"
+}
+
+function mapFWSessions2XNATPaths {
+    BaseDir=/data/XNAT/archive
+
+    awk -F / '{print "'"$BaseDir"'/"$2"/arc001/"$4}'    
+}
+
+# /data/XNAT/archive/NACC-SC/arc001/124287_20190124_3T => dwolklab/NACC-SC/124287/124287_20190124_3T
+function mapXNATPaths2FWSessions {
+    local Group="$1"
+    local XNATCSVFile="$2"
+    local Subject
+    local Session
+    
+    while read line
+    do
+	Session=$(echo "$line" | awk -F / '{print $NF}')
+	Project=$(echo "$line" | awk -F / '{print $5}')
+	Subject=$(grep ",$Session," "$XNATCSVFile" | cut -f 2 -d ,)
+	echo "${Group}/${Project}/${Subject}/${Session}"
+    done
+
+}
+
 function mapFWSessions2LougheadPaths {
     BaseDir=/data/jag/bbcp/Studies
     awk -F / '{print "'"$BaseDir"'/"$2"/Subjects/"$3"/"$4}'
 }
 
-function mapLoughheadPath2FWSessions {
+function mapLougheadPaths2FWSessions {
     local Group="$1"
     
     awk -F / '{print "'"$Group"'/"$6"/"$8"/"$9}'
@@ -199,10 +242,21 @@ then
     exit $?
 fi
 
-mapFWSessions2Paths=mapFWSessions2LougheadPaths
-mapPaths2FWSesssions=mapLougheadPaths2FWSessions
+prefix=xnatPrefix
+prefix=true
 
-Paths=$(getDicomDirsLoughead -g "$FWGroupID" -p "$FWProject" "$@" | sort)
+mapFWSessions2Paths=mapFWSessions2XNATPaths
+mapFWSessions2Paths=mapFWSessions2LougheadPaths
+
+mapPaths2FWSessions=mapXNATPaths2FWSessions
+mapPaths2FWSessions=mapLougheadPaths2FWSessions
+
+getDicomDirs=getDicomDirsXNAT
+getDicomDirs=getDicomDirsLoughead
+
+Paths=$("$getDicomDirs" -g "$FWGroupID" -p "$FWProject" "$@" | sort)
+
+PrefixInfo=( $("$prefix" "$FWGroupID" "$FWProject") )
 
 if [ -n "$opt_s" ]
 then
