WIP

diff --git a/xnat2fw/syncDicom2FW b/xnat2fw/syncDicom2FW
--- a/xnat2fw/syncDicom2FW
+++ b/xnat2fw/syncDicom2FW
@@ -13,7 +13,7 @@
 
 cmd=$(basename $0)
 
-syntax="$cmd [-D depth][-d dir] [-F]{-g FWGroupID}[-l][-n][-P XNATProject]{-p FlyWheelProject}[-q][-s cessionfile][-t NumberOfTransferThreads][-w NumberOfWorkerThreads][-v] [[XNATSession] ...]"
+syntax="$cmd [-b backend][-d dir] [-F]{-g FWGroupID}[-l][-n][-P DicomProjectName]{-p FWProjectName}[-q][-s sessionfile][-t NumberOfTransferThreads][-w NumberOfWorkerThreads][-v] [[DicomSession] ...]"
 
 : <<=cut
 =pod
@@ -24,7 +24,7 @@ xnat2fw - upload XNAT sessions to flywheel
 
 =head1 SYNOPSIS
 
-xnat2fw {-g FWGroupID} {-p FlyWheelProject} [-n][-P XNATProject][-q][-t NumberOfTransferThreads][-w NumberOfWorkerThreads][-v] [[XNATSession] ...]
+xnat2fw {-g FWGroupID} {-p FlyWheelProject} [-n][-P DicomProject][-q][-t NumberOfTransferThreads][-w NumberOfWorkerThreads][-v] [[DicomSession] ...]
 xnat2fw {-g FWGroupID} {-p FlyWheelProject} [-F]
 xnat2fw {-g FWGroupID} {-p FlyWheelProject} [-l]
 
@@ -50,10 +50,10 @@ List the remaining XNAT sessions to upload to the given Flywheel group and proje
 
 No-op.  Show what would have been done, but don\'t really do anything
 
-=item -P XNATProject
+=item -P DicomProject
 
 Overrides the Flywheel project specified with '-p'.
-Use this to upload XNAT sessions to a different Flywheel project.
+Use this to upload sessions to a different Flywheel project.
 
 =item -p
 
@@ -77,7 +77,7 @@ Verbose.  Show what commands are being run as we go.
 
 =back
 
-A space list of XNAT sessions may be given to xnat2fw.  Without this list, xnat2fw will
+A space list of Dicom sessions names may be given to xnat2fw.  Without this list, xnat2fw will
 generate a list of sessions still to be uploaded (use xnat2fw -l to see the list) and start uploading them.
 
 =cut
@@ -112,6 +112,12 @@ function syncDicom2FW {
 
 		read g Project Subject Session < <(echo "$Path" | "$sync2FWUtils" mapPaths2FWSessions "$FWGroupID" "${PrefixInfo[@]}" | tr '/' ' ')
 
+		if [ -z "$Project" -o -z "$Subject" -o -z "$Session" ]
+		then
+		    echo "$CmdName : '$Path' not mapped correctly.  Skipping."  1>&2
+		    continue
+		fi
+
 		#
 		# fw -q doesn't seem to do anything  Force it.
 		#	
@@ -133,14 +139,14 @@ function cleanup {
 #
 # *** Remove defaults for opt_g opt_p opt_P and verify they've been given on command line
 #
+opt_b=XNAT
 opt_t=4
 opt_w=2
-opt_D=3
 
-while getopts D:d:Fg:lnP:p:qs:t:w:v arg
+while getopts b:Fg:lnP:p:qs:t:w:v arg
 do
 	case "$arg" in 
-		D|d|F|f|g|l|n|P|p|q|s|t|w|v)
+		b|F|f|g|l|n|P|p|q|s|t|w|v)
 			eval "opt_${arg}=${OPTARG:=1}"
 			;;
 	esac
@@ -168,22 +174,17 @@ else
     exit 1
 fi
 
-if [ -n "$opt_D" ]
+if [ -n "$opt_P" ]
 then
-    Depth="$opt_D"
+    DicomProject="$opt_P"
+else
+    DicomProject="$opt_p"
 fi
 
-if [ -n "$opt_l" ]
-then
-    getFWSessions -g "$opt_g" "$opt_p"
-    exit $?
-fi
+sync2FWUtils=sync2FWUtils${opt_b}
+getDicomDirs=getDicomDirs${opt_b}
 
-sync2FWUtils=sync2FWUtilsXNAT
-sync2FWUtils=sync2FWUtilsLoughead
-getDicomDirs=getDicomDirsLoughead
-
-Paths=$("$getDicomDirs" -g "$FWGroupID" -p "$FWProject" "$@" | sort)
+Paths=$("$getDicomDirs" -g "$FWGroupID" -p "$DicomProject" "$@" | sort)
 
 PrefixInfo=( $("$sync2FWUtils" prefix "$FWGroupID" "$FWProject") )
 
@@ -197,6 +198,12 @@ fi
 FWPaths=$(echo "$FWSessions" | "$sync2FWUtils" mapFWSessions2Paths "$GroupID" "${PrefixInfo[@]}")
 
 SessionsMissingFromFlywheel=( $(diff <(echo "$Paths") <(echo "$FWPaths") | grep '<' | sed 's/< //') )
+
+if [ -n "$opt_l" ]
+then
+    echo "${SessionsMissingFromFlywheel[@]}" | tr ' ' '\n'
+    exit $?
+fi
 
 syncDicom2FW "$FWGroupID" "${SessionsMissingFromFlywheel[@]}"
 
